<?php

namespace ShopBundle\Repository;

/**
 * OrdersProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersProductsRepository extends \Doctrine\ORM\EntityRepository
{
}
