<?php

namespace ShopBundle\Repository;

/**
 * StaticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaticRepository extends \Doctrine\ORM\EntityRepository
{
}
