# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: ShopBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration,
                surname: form.type, alias: app_user_registration,
                postcode: form.type, alias: app_user_registration,
                city: form.type, alias: app_user_registration,
                street: form.type, alias: app_user_registration,
                tel: form.type, alias: app_user_registration,
                                                                                }


    app.form.profile:
        class: ShopBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: fos_user_profile_edit,
                surname: form.type, alias: fos_user_profile_edit,
                postcode: form.type, alias: fos_user_profile_edit,
                city: form.type, alias: fos_user_profile_edit,
                street: form.type, alias: fos_user_profile_edit,
                tel: form.type, alias: fos_user_profile_edit,
                                                                                }





#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
